name: clean_architecture_posts
description: Posts App With Clean Architecture

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2

  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.6.4
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  # Local cache
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
